"use client";

import React, { Suspense } from "react";
import UserHeader from "./UserHeader";
import UserTable from "./UserTable";
import { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Food Delivery Dashboard",
//   description: "Generated by create next app",
// };

export default function UsersPage() {
  return (
    <div className="overflow-y-scroll h-[90svh] flex flex-col gap-10 px-2 lg:px-10 py-6 lg:py-8 bg-gray-50">
      <Suspense fallback={<div>Loading...</div>}>
        <UserHeader />
      </Suspense>
      <Suspense fallback={<p>Loading...</p>}>
        <UserTable />
      </Suspense>
    </div>
  );
}
