import React, { Suspense } from "react";
import StoresHeader from "./StoresHeader";
import StoresTable from "./StoresTable";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Food Delivery Dashboard",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div className="overflow-y-scroll h-[90svh] lg:px-10 px-3 py-6 lg:py-8 bg-gray-50">
      <div className="flex flex-col gap-9">
        <Suspense fallback={<div>Loading...</div>}>
          <StoresHeader />
        </Suspense>

        <Suspense fallback={<div>Loading...</div>}>
          <StoresTable />
        </Suspense>
      </div>
    </div>
  );
}
