import { Metadata } from "next";
import Dashboard from "./components/dashboard/Dashboard";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Food Delivery Dashboard",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <main className="h-full">
      <div className="overflow-y-scroll h-[90svh]">
        <Suspense fallback={<p>Loading...</p>}>
          <Dashboard />
        </Suspense>
      </div>
    </main>
  );
}
