import { Metadata } from "next";
import Dashboard from "./components/dashboard/Dashboard";

export const metadata: Metadata = {
  title: "Food Delivery Dashboard",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <main className="h-full">
      <div className="overflow-y-scroll h-[90svh]">
        <Dashboard />
      </div>
    </main>
  );
}
