import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Food Delivery Dashboard",
  description: "Generated by create next app",
};

export default function SettingPage() {
  return (
    <div className="overflow-y-scroll h-[90svh] px-10 py-8 bg-gray-50">
      SettingPage
    </div>
  );
}
